### ISSUE TITLE
Login not sucessfull

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.wire.WireDesktop#1] opened 2018-10-18 23:05 UTC
I can log in the first time, I open Wire. When I close it and open it again, I see the following:

[Peek wire.zip](https://github.com/flathub/com.wire.WireDesktop/files/2493845/Peek.wire.zip)

**Comment by fbruetting** [comment] 2018-10-18 23:44
The thing is, that it loads for a short time, but then doesn’t load my state.

**Comment by x80486** [comment] 2018-10-21 17:33
So much sadness :disappointed:

I can't figure this one out! The Flatpak itself doesn't tell me anything useful (to my knowledge) when running it with any/all/combination of these settings `--log-session-bus`, `--log-system-bus` (even though these are not set/used), or `--verbose`.

Moreover, I can't think of an actual configuration setting that might be impeding the correct startup.

I also tried:

- Giving full `home` / `host` access (just in case)
- Previous releases of Wire
- Downgrading the runtime to `Freedesktop 1.6`
- Changing the the runtime to `GNOME 3.30`

...but nothing is different. Wire just can't continue loading the application's state. I'll keep trying some other tweaks for the time being waiting for them to upgrade to Electron `3.x` – not sure why I think the upgrade might solve the problem :crossed_fingers:

**Comment by fbruetting** [comment] 2018-10-21 17:35
Have you asked upstream? I think they should provide at least some help and suggestions, when you already support them by providing the Flatpak.

**Comment by x80486** [comment] 2018-10-21 17:42
Yeah, I'll ask them :+1: ...I'm already clueless anyway :wink:

I bet they can figure it out since the issue looks like part of the startup process. I'll file an issue there and see how it goes.

**Comment by x80486** [comment] 2018-10-21 21:38
OK, it looks like it's a Flatpak issue then. I'll try to confirm on the IRC and if so I'll close the issue in the `wire-desktop` repository since there is nothing they can do.

On copying the _application state_ I'm assuming you meant the conversations, right? If so, I think you can backup/restore them. With the Flatpak version there shouldn't be any folders/files on the user's home since everything should be stored in `$HOME/.var/app/com.wire.WireDesktop`. Restoring stuff might be possible by merging the folders that the AppImage is using with the ones on `$HOME/.var/app/com.wire.WireDesktop`.

**Comment by fbruetting** [comment] 2018-10-21 21:41
The SIGKILL problem only occurs if you shut the system down or it crashes! Closing via the window button should emit a normal SIGTERM just fine. I can recognize the difference in Spotify or Lollypop, is with SIGKILL, the songs played in the meantime get lost and both programs start at the last beginning, when you open them again.

**Comment by fbruetting** [comment] 2018-11-15 17:52
Any news on this?

I just reopened Wire-Flatpak after weeks and after decryption everything worked. Sadly, just until the next restart of the application. It’s still unusable…

**Comment by x80486** [comment] 2018-11-15 20:43
@fbruetting, I did some more testing after all this time (from time to time), I also asked in the IRC `#flatpak` channel, but I couldn't find any answer that resonate with this issue.

I think this might be something that needs to be fixed/improved at a different "level", and not by (or in) the packaging manifest. Moreover, I see the _same behavior_ (in the sense that processes are kept hanging around and don't get completely closed/killed) on Electron-based applications like `Slack`, `Atom`, `RocketChat`, to name a few...but I don't see that those are impacted at startup once restarted – apparently `Wire` is more _restricted_ in that matter.

I know that none of those tho paragraphs resolve the issue, but I'm open to alternatives/suggestions. I'm not sure what's actionable on my end here.

**Comment by fbruetting** [comment] 2018-11-17 01:35
> Yeah, I'll ask them +1 ...I'm already clueless anyway wink

Have you received an answer from the Wire guys in the meantime?

**Comment by x80486** [comment] 2018-11-17 16:10
Not really. I closed the issue. In my opinion, it's not something they can fix because the application works fine in such a way with the other packaging technologies, except in the Flatpak – and the same behavior can be observed in other applications also, although I haven't seen the same kind of impact as in Wire.

I think the issue is around what you were referring to in #1498.

**Comment by x80486** [comment] 2018-11-26 15:08
...just as an update: I reopened the issue (just in case) :rofl:, and so far, the input from Wire's contributors/developers is that the application's window is hidden/closed depending on presence (or not) of the system's tray area – among some other details.

Still, it's unclear to me how it does not behave in such a way when installed via APT, RPM, AppImage, etc. :smirk:

**Comment by alexjp** [comment] 2018-11-27 01:44
I am new to this issue, but to me it looks like its having problems with systray: When I first open wire, it logs in like it should ( if I exit it previouslly while logged in ).

The issue comes when I close the window ( not exit the app Ctrl+Q ) and then start wire again.

I new instance is open, I have then 2 wire systray icons, making login not work now.

**Comment by alexjp** [comment] 2018-11-27 10:02
BTW, this fixed wire-desktop login problems for me:
```
flatpak run --talk-name=com.canonical.AppMenu.Registrar --filesystem=/tmp com.wire.WireDesktop
```
when I add the --filesystem=/tmp, launching a second instance of wire-desktop, all it does is focus on the first window, and does not create a second instance. This makes it not logout from both initial instance

**Comment by nedrichards** [comment] 2018-11-27 17:56
Ah, if this is fixed by letting the app see TMP then you possibly want to set `TMPDIR=$XDG_CACHE_HOME` like these other apps di: https://github.com/search?p=1&q=org%3Aflathub+TMPDIR%3D%24XDG_CACHE_HOME&type=Code

**Comment by x80486** [comment] 2018-11-27 23:34
I've played with that setting for a while and I can't find a way to make it fail, although it only works correctly with `--filesystem=/tmp`. I can actually move forward with that! Works for me :rofl:

@nedrichards, do you have any reservations on not using `--filesystem=/tmp`; I tried with `exec env TMPDIR=$XDG_CACHE_HOME /app/Wire/wire-desktop "$@"` (and also as an `--env` setting in `finish-args`), but it doesn't like it.

**Comment by x80486** [comment] 2018-11-29 22:54
Now I'm testing in Arch Linux and it doesn't work :disappointed: ...still the same issue. Surprisingly it does work in a Fedora VM that I use to test all of this in general. I didn't expect a different behavior between distros.

In Arch Linux I see these error messages always:

```shell
[3:1129/173718.776548:ERROR:address_tracker_linux.cc(175)] Could not bind NETLINK socket: Address already in use (98)
[3:1129/173718.776623:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /usr/var/run/dbus/system_bus_socket: No such file or directory
```

...but not in Fedora (virtualized); and the only way to get rid of those is by killing everything-wire: `pkill -f wire`

In any case, I went ahead and build it this time inside Arch Linux with `--filesystem=/tmp` and it works! :tada:

So @TingPing, what would be the issue on using `--filesystem=/tmp` instead of `--env=TMPDIR=/var/tmp`?

**Comment by TingPing** [comment] 2018-11-30 00:10
> So @TingPing, what would be the issue on using --filesystem=/tmp instead of --env=TMPDIR=/var/tmp?

Its just a sandbox escape for no benefit. If `/var/tmp` doesn't work then go to setting `TMPDIR=$XDG_CACHE_HOME/tmp` like the first attempt.

There is *no* reason `/tmp` should be needed.

**Comment by TingPing** [comment] 2018-11-30 00:10
> [3:1129/173718.776623:ERROR:bus.cc(394)] Failed to connect to the bus: Failed to connect to socket /usr/var/run/dbus/system_bus_socket: No such file or directory


That is very unrelated.

**Comment by x80486** [comment] 2018-11-30 11:37
> Its just a sandbox escape for no benefit. If `/var/tmp` doesn't work then go to setting `TMPDIR=$XDG_CACHE_HOME/tmp` like the first attempt.
> 
> There is _no_ reason `/tmp` should be needed.

You were right. It works if I set `TMPDIR` to `$XDG_CACHE_HOME/tmp`, but for some **dark** reason I don't fully understand, if I use the `$XDG_CACHE_HOME` variable/reference in the `--env` setting (as `--env=TMPDIR=$XDG_CACHE_HOME/tmp`) it doesn't get resolved correctly – so maybe that doesn't actually work in such a way and I was trying to force it.

![screenshot from 2018-11-30 06-11-10](https://user-images.githubusercontent.com/34633617/49285896-c2646100-f466-11e8-9ade-37ab8b2c9b1e.png)

But if I put it inline: `"exec env TMPDIR=$XDG_CACHE_HOME/tmp /app/Wire/wire-desktop \"$@\""`...it just works fine.

What I see is that Wire (or maybe Electron applications in general) needs to create a sub-directory called: `.org.chromium.Chromium.XYZ` using a _temporary location_. I'm not sure how is that set in the application, but in the end, it uses the `TMPDIR` value, not accessible before...hence the failure.

**Closed** 2018-11-30 12:21 UTC
Labels: bug, help wanted

**Comment by fbruetting** [comment] 2018-11-30 22:19
GREAT! It also opens the application instantly, instead of the fucking AppImage needing 20 seconds. 🤣
