### ISSUE TITLE
Fautly tray icon implementation

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.wire.WireDesktop#9] opened 2018-12-01 18:39 UTC
```Fedora 29 Silverblue & Gnome 3.30.2```

* The icon is distorted in both normal and “unread notification” state (see images below).
* Clicking on it doesn’t switch to the Wire window.
* The icon is no child of the generic tray icon. This would lead to the icon displaying a bar at the very top of the icon when you hover with the mouse (see pointed out in the first image below). And I think this might also solve the above issues.
* I don’t know if/how you might solve this, but the AppImage version doesn’t have a problem here.
* Maybe you can look into how [Meteo](https://gitlab.com/bitseater/meteo) solves this.

![bildschirmfoto von 2018-12-01 19-34-32](https://user-images.githubusercontent.com/10520767/49331622-87fedf00-f5a0-11e8-8ef7-99dc130022b0.png)

![bildschirmfoto von 2018-12-01 19-35-54](https://user-images.githubusercontent.com/10520767/49331615-61d93f00-f5a0-11e8-968c-e0b4c0b2b4ee.png)

**Comment by x80486** [comment] 2018-12-01 21:33
So, I did install `Fedora Silverblue 29`. By default, the one that comes with `Boxes` uses `GNOME 3.30.1` – and I don't think that fraction will make a difference.

How do you go by reproducing this? Or better then, to have that tray bar? Do you install something else, like an extension? All I can see is that it's pretty much the same as any other `GNOME` desktop – with no system tray.

**Comment by fbruetting** [comment] 2018-12-02 21:33
Ah you need to install the shell extension `Topicons plus` for getting those back. By the way, if you transform that into an appindicator, you would need the shell extension `(k)statusnotifieritem/appindicator support` for getting those back.

**Comment by jocull** [comment] 2019-01-14 17:39
This happened to me also. `(k)statusnotifieritem` has been working fine for most things, but for some reason Wire as a flatpak doesn't work. However, their provided `*.AppImage` version works fine with this.

I also added `Topicons plus` to get it to appear, and that does work if it's a bit ugly.

**Comment by x80486** [comment] 2019-01-14 18:16
I'm running a VM with Fedora `Siverblue` 29; I installed `(k)statusnotifieritem/appindicator support` and `Topicons plus`...but still, the Flatpak behaves exactly the same as the AppImage in that regard: the icon is somehow _all borked_.

![image](https://user-images.githubusercontent.com/34633617/51130990-68dca980-17fc-11e9-9489-ec37e222cd3d.png)

Is it possible for you to update any of the answer(s) with a screenshot to see how this should look like? As  you can see in the screenshot, for me, the AppImage behaves exactly the same. Moreover, it only has focus on that tray-bar icon for a while, after some time (or after something I'm doing clicking here and there) it doesn't provide me again with the menu options: `Open` / `Quit`. I've notice that sometimes the focus is not even accurate around the icon.

**Comment by x80486** [comment] 2019-05-02 14:17
@jocull and @fbruetting, I'll close this one since it's not actually a problem with the Flatpak, but and upstream issue.

You can reopen it later if, for any reason(s), it becomes an issue specifically with the Flatpak packaging.

**Closed by x80486** 2019-05-02 14:17 UTC
